#!/bin/bash

#DATE=`date +%Y%m%d%M%S`
HOMEDIR=$(pwd)
DATE=`date +%Y%m%d`
TMPDIR=/tmp
PACKAGENAME=ftb++
VERSION=v$DATE
PACKAGENAMEVERSION=$PACKAGENAME-$VERSION
TARGETDIR=target
RESOURCEDIR=resources/ftb++
PACKAGEVERSIONJAR=$PACKAGENAMEVERSION.jar
PACKAGEVERSIONARC=$PACKAGENAMEVERSION.tar.gz
CMDFILE=ftb++.sh
READMEFILE=FTB++.README

# clean and config
rm -r $TMPDIR/$PACKAGENAMEVERSION
mkdir $TMPDIR/$PACKAGENAMEVERSION
mkdir $TMPDIR/$PACKAGENAMEVERSION/lib

# copy
cp $TARGETDIR/$PACKAGEVERSIONJAR $TMPDIR/$PACKAGENAMEVERSION/lib
cp $RESOURCEDIR/$CMDFILE $TMPDIR/$PACKAGENAMEVERSION/
cp $READMEFILE $TMPDIR/$PACKAGENAMEVERSION/README

# archive
cd $TMPDIR
tar -cvzf $PACKAGEVERSIONARC $PACKAGENAMEVERSION
cp $PACKAGEVERSIONARC $HOMEDIR/$TARGETDIR

# test
rm -r $TMPDIR/tmp-$VERSION
mkdir $TMPDIR/tmp-$VERSION
cd $TMPDIR/tmp-$VERSION
cp ../$PACKAGEVERSIONARC $TMPDIR/tmp-$VERSION
tar -xvzf $PACKAGEVERSIONARC
cd $PACKAGENAMEVERSION
# java command
