//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 01:36:56 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.lina.univ-nantes.fr/uima/annotationmapper", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.univnantes.lina.uima.mapper.rules.JAXB;
